### ISSUE TITLE
Confusion about long-polling in the HTMX tutorial

### ISSUE THREAD

**Issue by FantasyTeddy** [JetBrains/guide#13]
Hi, I'm currently reading through the excellent [HTMX for ASP.NET Core Developers](https://www.jetbrains.com/dotnet/guide/tutorials/htmx-aspnetcore/) tutorial and I'm a little bit confused about the term "long-polling" in the [Long-Polling to get recent updates](https://www.jetbrains.com/dotnet/guide/tutorials/htmx-aspnetcore/long-polling/) chapter.

My understanding of [long-polling](https://en.wikipedia.org/wiki/Push_technology#Long_polling) is, that it does not require constant client-side polling (as in the tutorial example), but allows the server to delay its response until something "interesting" happens.

For the provided stock value example, I would have expected the following:
- On the client-side, the `hx-trigger` should be (close to) immediate.
- ... and on the server-side, the GET request should probably be asynchronous and wait for some kind of "stock value changed" event until it sends a response.

Is my understanding of long-polling wrong, or is the example just "polling"?

**Comment by pauleveritt** [comment]
Nudge @khalidabuhakmeh

**Comment by khalidabuhakmeh** [comment]
I guess I've been using the term interchangeably, but there seems to be a distinction. You are correct. Thanks for teaching me something.

**Comment by FantasyTeddy** [comment]
Thank you for confirming. I'm glad I did not misinterpret something :)
