### ISSUE TITLE
https://www.jetbrains.com/idea/guide/rss.xml is dead

### ISSUE THREAD

**Issue by ste-xx** [JetBrains/guide#9]
Hi,

since a view days the rss feed is not reachable anymore.

Has the url changed? I did not find any feed link on the guide page.

**Comment by pauleveritt** [comment]
Thanks for reporting this. We switched from Gatsby to 11ty and looks like we tripped on this during transition.

The `rss.xml` link is getting asset-ified:

```
<link rel="alternate" type="application/rss+xml" title="IntelliJ IDEA Guide RSS Feed" 
href="/idea/guide/assets/rss-6397d51b.xml"
```

**Comment by maartenba** [comment]
The issue should now be fixed (give or take a few minutes because of CDN caching, depending on which edge server you end up on) - https://www.jetbrains.com/idea/guide/rss.xml.

Thanks @khalidabuhakmeh for the fast turnaround!
